/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACascader: typeof import('ant-design-vue/es')['Cascader']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AImagePreviewGroup: typeof import('ant-design-vue/es')['ImagePreviewGroup']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATimePicker: typeof import('ant-design-vue/es')['TimePicker']
    ATimeRangePicker: typeof import('ant-design-vue/es')['TimeRangePicker']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    DateTimeRangePicker: typeof import('./src/components/Comp/dateTimeRangePicker/index.vue')['default']
    FileSelect: typeof import('./src/components/FileSelect/index.vue')['default']
    Form: typeof import('./src/components/Comp/form/index.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Menu: typeof import('./src/components/Menu/index.vue')['default']
    PopUpFormBox: typeof import('./src/components/Comp/popUpFormBox/index.vue')['default']
    Preview: typeof import('./src/components/Comp/upload/components/Preview.vue')['default']
    PreviewDialog: typeof import('./src/components/Comp/PreviewDialog/index.vue')['default']
    PullToLoadSelect: typeof import('./src/components/Comp/pullToLoadSelect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Comp/table/index.vue')['default']
    TableButton: typeof import('./src/components/Comp/table/tableButton/index.vue')['default']
    TableSearch: typeof import('./src/components/Comp/table/tableSearch/index.vue')['default']
    TimeRangePicker: typeof import('./src/components/Comp/timeRangePicker/index.vue')['default']
    Upload: typeof import('./src/components/Comp/upload/index.vue')['default']
  }
}
